CREATE DATABASE libretto_iscrizioni;
USE libretto_iscrizioni;

CREATE TABLE cdl (
id INTEGER PRIMARY KEY auto_increment,
nome VARCHAR(30) NOT NULL
);

CREATE TABLE studente (
matricola INTEGER PRIMARY KEY auto_increment,
nome VARCHAR(20) NOT NULL,
cognome VARCHAR(20) NOT NULL,
cdl INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (cdl) REFERENCES cdl(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE materia (
id INTEGER PRIMARY KEY auto_increment,
nome VARCHAR(25) NOT NULL
);

CREATE TABLE appello (
id INTEGER PRIMARY KEY auto_increment,
data DATE NOT NULL,
materia INTEGER NOT NULL,
cdl INTEGER NOT NULL,
cfu INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY (materia) REFERENCES materia(id) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FOREIGN KEY (cdl) REFERENCES cdl(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE iscrizione (
voto INTEGER,
studente INTEGER NOT NULL,
appello INTEGER NOT NULL,
PRIMARY KEY (studente, appello),
CONSTRAINT FOREIGN KEY (studente) REFERENCES studente(matricola) ON UPDATE RESTRICT ON DELETE RESTRICT,
CONSTRAINT FOREIGN KEY (appello) REFERENCES appello(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);


